### ISSUE TITLE
Need another meeting before 29th March

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/london-community-outreach#15]
We need to vote on our committee charter so that it can be put forward as a proposal for the next business meeting

i.e. before 29th March

**Comment by emilyb7** [comment]
If this is just because of the charter, can we vote online instead of
having a special meeting? Or is there something else? In which case, Monday
during biz Dev hours again?

**Comment by jsms90** [comment]
Absolutely fine by me. But half of our committee will be en route to the Spotlight Cafe

**Comment by emilyb7** [comment]
Oh yeah of course! Well, I'm up for online voting.

**Comment by jsms90** [comment]
I think it's just worth setting a time & date, so that we can ensure that everyone does vote. Even if it's just to abstain.

Maybe we should do this during the next week's bis dev hours. It doesn't take 2 minutes for the Spotlight Cafe crew to vote online. No hangouts necessary ;)
