### ISSUE TITLE
Confirm suitability of the Spotlight Cafe

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/london-community-outreach#16]
As was agreed at the previous business meeting, Dan Zooey and Yvonne will be going to the Spotlight Cafe on Monday 13th to confirm the suitability of the location for the school workshops:
+ number of computers
+ internet speed is sufficient at 4-6pm on Mondays to handle web dev work on 10 computers
+ Chrome installed / can be installed
+ can install text editor (or at least use c9.io)
+ speak to the staff, just to introduce who we are

Can I suggest that everyone wears t-shirts? @sofer if you weren't copied in on the email were I was given the phone number of our contact person there, please let me know. It would probably be nice if we rang them up in advance to let them know we are coming on Monday to speak with them :+1:

**Comment by sofer** [comment]
@jsms90 I believe Ed has followed up with contacting the cafe.

**Comment by jsms90** [comment]
Completely positive. 16 Macs, enough space for everyone :+1:
