### ISSUE TITLE
Prepare workshops

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/london-community-outreach#17]
Preparation to be stared at the Spotlight Cafe visit on Monday 13th

Ideally these would be finished 1 week prior to the start date of the workshops, to give committee members time to "user test" them

**Comment by sofer** [comment]
@ZooeyMiller @yvonne-liu My hope is that we will be able to start and end the preparation on Monday and to base the workshop on https://github.com/foundersandcoders/london-programme/issues/28. Looking forward to this. It's going to be good.

**Comment by jsms90** [comment]
https://github.com/yvonne-liu/spotlight-workshop

**Comment by jsms90** [comment]
Closing this issue, as progress is being dealt with via the repo above

**Comment by yvonne-liu** [comment]
Update repo location 😉  https://github.com/foundersandcoders/spotlight-workshop
