### ISSUE TITLE
Publish our school workshops on eventbrite?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/london-community-outreach#19]
@sofer you mentioned this to me today after your phone call with Ed Cox, as an alternative to flyers/posters?

Does Ed know that we are not producing flyers?
Does FAC have an eventbrite account?
Are there any negative implications of publicising this event online (thinking about responsibility of care)?

**Comment by sofer** [comment]
@jsms90 Ed called the other day. He knows about the flyers. We do have an eventbrite account. We will set the event to "private", so it won't be searchable by the general public. It shold be no less secure than a google form.

**Comment by sofer** [comment]
Placeholder published (but not searchable): https://www.eventbrite.co.uk/e/founders-coders-coding-workshop-tickets-32759879682

**Comment by sofer** [comment]
Published and receiving sign ups.
