### ISSUE TITLE
Code First: Girls JavaScript Masterclass

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/london-community-outreach#2]
> Rufus is a Software Engineer at ThoughtWorks and has started to create the curriculum for our Masterclass. It would be great to find out which FAC cohort members would like to be involved in helping us create the curriculum and also assist on teaching on the Masterclass.
>
> We've now got a private repo setup with the curriculum as it stands, so once you know who would like to be involved if you could send me their email addresses & github username we can add them.

If anyone is interested in joining ThoughtWorks, this might be a good opportunity to get to know them from the inside (Hint: we have not yet got a hiring relationship with them yet, so if you get involved, part of your task will be to persuade them that they should have one).

**Comment by sofer** [comment]
@sohilpandya are you up for holding onto this relationship for now?

**Comment by mk4111** [comment]
@sofer and @sohilpandya - I'd be interested in participating too, but have a few questions which I think can only be resolved once we have a chat with Rufus...?

**Comment by sohilpandya** [comment]
@sofer thanks for the email, could you please intro us so that we can have the first chat? ☺

**Comment by astroash** [comment]
@sofer @sohilpandya @AseelM Do you know what happened with this? Can we close this issue?

**Comment by sofer** [comment]
@astroash good question. @sohilpandya or @mk4111 will be able to tell us more.

**Comment by AseelM** [comment]
This collaboration has been suspended by Code First:Girls, because the curriculum wasn't developed in time.
