### ISSUE TITLE
Get update on status of FAC10's DBS checks

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/london-community-outreach#20]
@yvonne-liu and @ZooeyMiller to communicate with FAC10
@jsms90 to communicate with Stemnet

We need to know who has their enhanced disclosure forms by 20th, so that we can ensure that we have 4 cohort members attending the first workshop on 27th

**Comment by yvonne-liu** [comment]
I've asked everyone in FAC10 already -- will update the checklist as I go and follow up in a week (or less) to check on the people who don't have their clearance.

**Comment by yvonne-liu** [comment]
- [x] Akin 
- [x] Alexis
- [x] Alice
- [x] Antonio
- [x] Finn 
- [x] Jessica
- [x] Joey
- [ ] Lucy
- [x] Maja
- [ ] Martha 
- [x] Oliver
- [x] Philippa
- [x] Piotr 
- [x] Samatar 
- [ ] Zooey 
- [ ] Yvonne

**Comment by yvonne-liu** [comment]
@jsms90 by four cohort for the first workshop you mean six, right? Since now we're only doing three workshops I thought we'd have six mentors at each workshop? Thanks.

**Comment by jsms90** [comment]
@yvonne-liu :+1: I didn't know whether we were doing 3 or 4 workshops in the end

**Comment by astroash** [comment]
@yvonne-liu @ZooeyMiller  Do you know the final outcome of this? Have you gotten in touch with Stemnet? 😀

**Comment by yvonne-liu** [comment]
Hi @astroash sorry I don't understand your question!

**Comment by jsms90** [comment]
@astroash @yvonne-liu Sorry, it says in the top comment that that was my responsibility.

I've just emailed Jenny Clay from Stemnet to see if she needed any more info from us e.g. a list of which Ambassadors attended on which days. But I don't remember exactly what (if anything) Stemnet needs.

@yvonne-liu Did you ever have any communication with her? I seem to remember you had to give a bunch of info to the Spotlight Cafe. Is that right? Do you have a list of who attended and when?

**Comment by yvonne-liu** [comment]
@jsms90 @astroash 

First spotlight on March 27th:
Yvonne Liu (No DBS during this session)
Zooey Miller (No DBS during this session)
Oliver Phillips 
Samatar Axmed 
Jessica Salmon 
Antonio Trabalza 
Alexis Lui 
Jen Spencer

Second Spotlight on April 3rd: 
Yvonne Liu (No DBS during this session)
Zooey Miller (No DBS during this session)
Finn Hodgkin 
Joanna Scott 
Maja Kudlicka
Alice Carr 
Piotr Berebecki

Third and final Spotlight on April 10th:
Yvonne Liu (No DBS during this session)
Zooey Miller 
Philippa Bywater 
Martha Ciobaniuc (No DBS during this session)
Akinola Sowemimo

**Comment by ZooeyMiller** [comment]
Closing this issue as it is no longer relevant. All DBS checks were completed and the Spotlight workshops are over for now.
