### ISSUE TITLE
Admin rights for meetup gitter channels

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/london-community-outreach#25]
In order for the hosts of our meetups to add participants to our gitter channels, they need to be given admin rights to the Coding for Everyone and Coding for Women channels. Is it remotely problematic to give everyone that goes through FAC admin rights to these organisations?

If not, doing this should become an action point for this committee.

If so, can this somehow be authorised automatically when a meetup participant signs the google form that we are creating? Or, the submission of this form trigger a notification (email?) to be sent to C4E / C4W admin(s)?

**Comment by iteles** [comment]
I believe Founders & Coders no longer uses Gitter, so I'm closing this issue.
