### ISSUE TITLE
Improvements to signup form

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/london-community-outreach#26]
Turn these into dropdown lists:
+ [ ] **"Which topic do you want to work on?"**
  + Codecademy (complete beginner)
  + Free Code Camp projects
  + Solving and creating Codewars katas
  + Eloquent Javascript
  + CS50

We are getting lots of answers that say "_Javascript_", which doesn't help us.
We also get "_my application_", which doesn't tell us which of the above activities are popular. It also doesn't add much beyond this question: "_Are you thinking about applying to the Founders & Coders coding bootcamp?_".

+ [ ] **"How did you find out about Founders & Coders?"**
  + Email / serach via www.meetup.com
  + Search engine
  + Medium article
  + Post on social media
  + Referral from someone at another meetup  
Which meetup? ...................
  + From a friend (word of mouth)
  + Other .....................

Standardising the format of this reply would make it much easier for us to analyse numbers.

**Comment by PiotrBerebecki** [comment]
@joeylouise and I have just updated the sign-up form: https://docs.google.com/forms/d/1iKpWMssbjBriEFBS3DtZVFoUxo_KYN9ygmVnNwqHuUc/edit
