### ISSUE TITLE
Career workshop with Year 9 Students

### ISSUE THREAD

**Issue by sohilpandya** [foundersandcoders/london-community-outreach#28]
@minaorangina's sister is looking to make contact with us so that she can get a career workshop going for a local school.

She works for an education charity to help disadvantaged kids get into uni/career. 

@minaorangina the floor is yours, would love some more detail in this issue. 😄

**Comment by minaorangina** [comment]
Yep, so her charity does a bunch of stuff with social mobility and going to uni.  Part of that includes workshops for kids who might be thinking about what options they want to take for GCSE, and to give them a taster of the different sorts of careers that exist out there.

My sister mentioned a workshop coming up this Friday (5th) which would be 90 mins long, somewhere in Newham.  Idea would be to talk about how you got into your career, why it's cool, then do something practical - get them to code something up.  

But generally speaking I think she's keen to get in touch with FAC generally about ways of collaborating, even if it's not this time round.  She's based up the road too, so could be a good start for community outreach stuff generally?

Happy to make an email intro 👌

**Comment by astroash** [comment]
@minaorangina is this this still something that FAC can get involved with or are we too late?

**Comment by minaorangina** [comment]
@astroash No definitely not too late, though there won't be much going on now with the school holidays round the corner.  I'll talk to my sister and maybe can get something set up for the next academic year?

**Comment by astroash** [comment]
@minaorangina that would be great :+1:  Let me know what she says, I'd be happy to have a chat with her to discuss what they would be looking for curriculum wise.

**Comment by minaorangina** [comment]
@astroash Cool, what's your email? My sister said it might be good to have a chat in person.  I can introduce you via email and you two can take it from there?

**Comment by astroash** [comment]
@minaorangina, sounds like a fab idea! Pass on my email address to her - astroaisha@gmail.com

**Comment by astroash** [comment]
Contacted Sharon about FAC getting involved with [IntoUniversity](http://intouniversity.org/content/community-volunteering)

**Comment by jsms90** [comment]
This issue was moved to foundersandcoders/london-programme#473
