### ISSUE TITLE
Request to host a hackathon with Founders & Coders in July

### ISSUE THREAD

**Issue by emilyb7** [foundersandcoders/london-community-outreach#34]
Someone I met at the London Tech for Good meetup on Monday has got in touch and asked if we'd be interested in jointly hosting a one-day event, details here. Please let me know if anyone's interested!

The person I spoke to is familiar with the FAC model and has been to Coding for Everyone in the past. She seems enthusiastic and I'm sure she'd be interested in future collaborations if this one doesn't work out :) 

> The event would be a satellite event to HomelessHack which is a hackathon working with data on homelessness. Possibly on the 8th July, working together with a person from the HomelessHack organising team I would be running a one-day event (say 10-18) looking at data on homelessness from East London. The results should be dataviz or small web apps that provide help to charities or to homeless people. I don't have any budget but if the space requires we could ask for a £5 optional donation, I think that's not too much for those who are interested in joining us. A max of 15 people. Also, I do this on a voluntary basis and am happy to run similar charitable hack days if Founders & Coders is interested in hosting them and inviting alumni and friends. :) Contact: marietta@boun.cr.

**Comment by emilyb7** [comment]
@jsms90, sorry for randomly assigning this to you. I don't know who else to ask about community related things!!

**Comment by lucymonie** [comment]
@emilyb7 your contact might like to try and join this: https://www.eventbrite.com/e/homelesshack-tickets-32406738427

**Comment by emilyb7** [comment]
@lucymonie i think she knows about that one and wants to create a kind of smaller, follow-on event :)

**Comment by lucymonie** [comment]
Oh right - sorry I just saw that the quoted part referred to that. Do you know who she's in touch with from HomelessHack? One of the people from Centrepoint is one of the organisers so if she doesn't already know her, I could put them in touch.

**Comment by astroash** [comment]
Fixed here https://github.com/foundersandcoders/london-programme/issues/256
