### ISSUE TITLE
Keys for 14!

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/london-community-outreach#7]
I'll get 'em.

**Comment by jsms90** [comment]
@sofer let's make sure it's a good key that gets cut. FAC10 were having trouble locking up tonight after Coding for Women

**Comment by jsms90** [comment]
@sofer Has this been done? Last night the ones running C4E didn't have a key

**Comment by sofer** [comment]
@jsms yes, sorry, I have a couple and can provide more, if needed. People just have to ask.
