### ISSUE TITLE
Sign up form for C4E and C4W

### ISSUE THREAD

**Issue by joeylouise** [foundersandcoders/london-community-outreach#8]
First name 
Last name (optional)
Github handle
Email address (optional - only to send for thank you for coming)
Which topic they want to work on
How they found out about us --> dropdown list (like on application form)
Whether they are thinking about applying to FAC
Postcode (optional)
(Checkbox --> is it ok if we send you emails in the future)

**Comment by jsms90** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSe9XBPXkVLoFOOz-Koepqnj-LrTQgtRX-vlzBFI8X-OmBPGiQ/viewform

**Comment by jsms90** [comment]
At Coding for Everyone last night, we had people signing up using FAC's iPad

**Comment by jsms90** [comment]
@joeylouise What happened to
> (Checkbox --> is it ok if we send you emails in the future)

?
